layout_spectrum: 0.349828
color:
  saturation: 0.6195685
  lightness: 0.3234282
  brandStrength: 0.4946237
  brandColors:
    - '#FFFFFF'
    - '#1F1E1F'
    - '#BC9B91'
    - '#A2BDD1'
    - '#5C6E77'
  rhythmicContrast: 0.3771102
typography_spectrum: 0.5143369
name: Madi
